import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Plus, Trash2, Save, Printer } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface Medicine {
  name: string;
  dose: string;
  frequency: string;
  duration: string;
  instructions: string;
}

interface Vitals {
  bp?: string;
  temperature?: string;
  pulse?: string;
  weight?: string;
  spo2?: string;
}

interface DigitalPrescriptionProps {
  patientId: string;
  appointmentId?: string;
  onSave: () => Promise<void>;
  onCancel: () => void;
}

export function DigitalPrescription({ patientId, appointmentId, onSave, onCancel }: DigitalPrescriptionProps) {
  const { toast } = useToast();
  const [diagnosis, setDiagnosis] = useState("");
  const [chiefComplaint, setChiefComplaint] = useState("");
  const [advice, setAdvice] = useState("");
  const [followUpDate, setFollowUpDate] = useState("");
  const [medicines, setMedicines] = useState<Medicine[]>([
    { name: "", dose: "", frequency: "", duration: "", instructions: "" }
  ]);
  const [vitals, setVitals] = useState<Vitals>({});
  const [isSaving, setIsSaving] = useState(false);

  const addMedicine = () => {
    setMedicines([...medicines, { name: "", dose: "", frequency: "", duration: "", instructions: "" }]);
  };

  const removeMedicine = (index: number) => {
    setMedicines(medicines.filter((_, i) => i !== index));
  };

  const updateMedicine = (index: number, field: keyof Medicine, value: string) => {
    const updated = [...medicines];
    updated[index][field] = value;
    setMedicines(updated);
  };

  const updateVital = (field: keyof Vitals, value: string) => {
    setVitals({ ...vitals, [field]: value });
  };

  const handleSave = async () => {
    try {
      setIsSaving(true);

      // Get current doctor
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      const { data: doctor } = await supabase
        .from('doctors')
        .select('id')
        .eq('user_id', user.id)
        .single();

      if (!doctor) throw new Error("Doctor profile not found");

      // Validate medicines
      const validMedicines = medicines.filter(m => m.name.trim() !== "");
      if (validMedicines.length === 0) {
        toast({
          title: "Error",
          description: "Please add at least one medicine",
          variant: "destructive",
        });
        return;
      }

      // Save prescription (prescription_id is auto-generated by database trigger)
      const { error } = await (supabase as any)
        .from('prescriptions')
        .insert([{
          patient_id: patientId,
          doctor_id: doctor.id,
          appointment_id: appointmentId,
          diagnosis,
          chief_complaint: chiefComplaint,
          medicines: validMedicines,
          advice,
          follow_up_date: followUpDate || null,
          vitals: vitals,
        }]);

      if (error) throw error;

      await onSave();
    } catch (error: any) {
      toast({
        title: "Error saving prescription",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card className="p-6">
        <h3 className="text-lg font-semibold mb-4">Vitals</h3>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          <div>
            <Label htmlFor="bp">Blood Pressure</Label>
            <Input
              id="bp"
              placeholder="120/80"
              value={vitals.bp || ""}
              onChange={(e) => updateVital("bp", e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="temperature">Temperature (°F)</Label>
            <Input
              id="temperature"
              placeholder="98.6"
              value={vitals.temperature || ""}
              onChange={(e) => updateVital("temperature", e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="pulse">Pulse (bpm)</Label>
            <Input
              id="pulse"
              placeholder="72"
              value={vitals.pulse || ""}
              onChange={(e) => updateVital("pulse", e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="weight">Weight (kg)</Label>
            <Input
              id="weight"
              placeholder="70"
              value={vitals.weight || ""}
              onChange={(e) => updateVital("weight", e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="spo2">SpO2 (%)</Label>
            <Input
              id="spo2"
              placeholder="98"
              value={vitals.spo2 || ""}
              onChange={(e) => updateVital("spo2", e.target.value)}
            />
          </div>
        </div>
      </Card>

      <Card className="p-6">
        <div className="space-y-4">
          <div>
            <Label htmlFor="complaint">Chief Complaint</Label>
            <Input
              id="complaint"
              placeholder="Patient's main complaint"
              value={chiefComplaint}
              onChange={(e) => setChiefComplaint(e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="diagnosis">Diagnosis</Label>
            <Textarea
              id="diagnosis"
              placeholder="Enter diagnosis"
              value={diagnosis}
              onChange={(e) => setDiagnosis(e.target.value)}
              rows={2}
            />
          </div>
        </div>
      </Card>

      <Card className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold">Medicines</h3>
          <Button onClick={addMedicine} size="sm">
            <Plus className="mr-2 h-4 w-4" />
            Add Medicine
          </Button>
        </div>
        <div className="space-y-4">
          {medicines.map((medicine, index) => (
            <div key={index} className="border rounded-lg p-4 space-y-3">
              <div className="flex items-center justify-between">
                <h4 className="font-medium">Medicine {index + 1}</h4>
                {medicines.length > 1 && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => removeMedicine(index)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                )}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div>
                  <Label>Medicine Name</Label>
                  <Input
                    placeholder="e.g., Paracetamol 500mg"
                    value={medicine.name}
                    onChange={(e) => updateMedicine(index, "name", e.target.value)}
                  />
                </div>
                <div>
                  <Label>Dose</Label>
                  <Input
                    placeholder="e.g., 1 tablet"
                    value={medicine.dose}
                    onChange={(e) => updateMedicine(index, "dose", e.target.value)}
                  />
                </div>
                <div>
                  <Label>Frequency</Label>
                  <Input
                    placeholder="e.g., 3 times a day"
                    value={medicine.frequency}
                    onChange={(e) => updateMedicine(index, "frequency", e.target.value)}
                  />
                </div>
                <div>
                  <Label>Duration</Label>
                  <Input
                    placeholder="e.g., 5 days"
                    value={medicine.duration}
                    onChange={(e) => updateMedicine(index, "duration", e.target.value)}
                  />
                </div>
                <div className="md:col-span-2">
                  <Label>Instructions</Label>
                  <Input
                    placeholder="e.g., After food"
                    value={medicine.instructions}
                    onChange={(e) => updateMedicine(index, "instructions", e.target.value)}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </Card>

      <Card className="p-6">
        <div className="space-y-4">
          <div>
            <Label htmlFor="advice">Advice & Instructions</Label>
            <Textarea
              id="advice"
              placeholder="General advice and instructions for the patient"
              value={advice}
              onChange={(e) => setAdvice(e.target.value)}
              rows={3}
            />
          </div>
          <div>
            <Label htmlFor="followup">Follow-up Date</Label>
            <Input
              id="followup"
              type="date"
              value={followUpDate}
              onChange={(e) => setFollowUpDate(e.target.value)}
            />
          </div>
        </div>
      </Card>

      <div className="flex justify-end gap-3">
        <Button variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button onClick={handleSave} disabled={isSaving}>
          <Save className="mr-2 h-4 w-4" />
          {isSaving ? "Saving..." : "Save Prescription"}
        </Button>
      </div>
    </div>
  );
}
