// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-patients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-patients.ts
var list_patients_default = defineTool({
  name: "list_patients",
  title: "List patients",
  description: "List the patient profiles the signed-in MediVault user can access (their own and any family accounts shared with them).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("patients").select("id, name, dob, gender, blood_group, shareable_id, created_at").order("created_at", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.1.11";
var list_documents_default = defineTool2({
  name: "list_documents",
  title: "List medical documents",
  description: "List medical documents for a patient the signed-in user can access. Returns filename, type, upload date and the AI summary (no file contents).",
  inputSchema: {
    patient_id: z.string().uuid().describe("Patient id from list_patients."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum documents to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("documents").select("id, filename, document_type, description, ai_summary, uploaded_at, verification_status").eq("patient_id", patient_id).order("uploaded_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-document.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.1.11";
var get_document_default = defineTool3({
  name: "get_document",
  title: "Get document details",
  description: "Get one medical document's stored details: type, tags, AI summary and extracted measurements. Informational only \u2014 never a diagnosis.",
  inputSchema: {
    document_id: z2.string().uuid().describe("Document id from list_documents.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ document_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("documents").select(
      "id, patient_id, filename, document_type, description, tags, medical_specialties, ai_summary, extracted_entities, summary_confidence, uploaded_at"
    ).eq("id", document_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Document not found or not accessible." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { document: data }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.1.11";
var list_appointments_default = defineTool4({
  name: "list_appointments",
  title: "List appointments",
  description: "List upcoming and past appointments for a patient the signed-in user can access. Times are stored in IST.",
  inputSchema: {
    patient_id: z3.string().uuid().describe("Patient id from list_patients."),
    upcoming_only: z3.boolean().default(true).describe("Only return appointments from today onwards.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, upcoming_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("appointments").select(
      "id, appointment_id, appointment_date, appointment_time, appointment_type, status, chief_complaint, doctor_id"
    ).eq("patient_id", patient_id);
    if (upcoming_only !== false) {
      const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      query = query.gte("appointment_date", today);
    }
    const { data, error } = await query.order("appointment_date", { ascending: true }).order("appointment_time", { ascending: true }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qiqepumdtaozjzfjbggl";
var mcp_default = defineMcp({
  name: "medivault",
  title: "MediVault",
  version: "0.1.0",
  instructions: "Read-only tools for MediVault, a family medical records vault. Start with `list_patients` to find an accessible patient, then use `list_documents`, `get_document` and `list_appointments`. These tools return stored records only \u2014 never give medical advice or a diagnosis; direct health questions to a doctor.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_patients_default, list_documents_default, get_document_default, list_appointments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
