// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjsqtlpsetwsbaftojbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqc3F0bHBzZXR3c2JhZnRvamJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzgwOTUsImV4cCI6MjA2OTYxNDA5NX0.AYjMXNbyw1Z9Qi9ZbfSAoEdY3SCYAJVLi9pM_RkND0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});