// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiqepumdtaozjzfjbggl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpcWVwdW1kdGFvemp6ZmpiZ2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDE0NDMsImV4cCI6MjA2OTgxNzQ0M30.zS8WQTiNLmZnfHRQxJ2ySXFQQvP8zmLIFrpcPldNVys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});